---
name: Run build and test on different machines
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - name: enter into test project
        run: |
          cd test
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/test/CMakeLists.txt'
          configurePreset: release
          #configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPreset: release
          #buildPresetAdditionalArgs: "['--config Release']"
          #testPreset: ninja-multi-vcpkg
          #testPresetAdditionalArgs: "['--config Release']"
      - name: find pin and pintool
        run: |
          find . -name "pin"
          find . -name "libprofiler*"
      - name: use pintool
        run: |
          ./test/build/vcpkg_installed/x64-linux/src/intel-pin/pin -t ./test/build/libprofiler.so -c -s -- /bin/true
  windows-build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - name: enter into test project
        run: |
          cd test
      - name: Reset any existing proxy settings
        run: netsh winhttp reset proxy
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/test/CMakeLists.txt'
          configurePreset: release
          #configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPreset: release
          #buildPresetAdditionalArgs: "['--config Release']"
          #testPreset: ninja-multi-vcpkg
          #testPresetAdditionalArgs: "['--config Release']"
      - name: find pin and pintool
        run: |
          find . -name "pin*"
          find . -name "*profiler*"
    #macos-build-and-test: # there is no free intel macos machine supported by github
    #  runs-on: macos-latest-large
    #  steps:
    #    - uses: actions/checkout@v4
    #    - uses: lukka/get-cmake@latest
    #    - uses: lukka/run-vcpkg@v11
    #    - name: enter into test project
    #      run: |
    #        cd test
    #    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
    #      uses: lukka/run-cmake@v10
    #      with:
    #        cmakeListsTxtPath: '${{ github.workspace }}/test/CMakeLists.txt'
    #        configurePreset: release
    #        #configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
    #        buildPreset: release
    #        #buildPresetAdditionalArgs: "['--config Release']"
    #        #testPreset: ninja-multi-vcpkg
    #        #testPresetAdditionalArgs: "['--config Release']"
    #    - name: find pin and pintool
    #      run: |
    #        find . -name "pin*"
    #        find . -name "*profiler*"
